Allow cross-referencing in nav
backstage/mkdocs-monorepo-plugin pull request #94
Opened 2023-02-21 21:16 UTC by haneul

Sometimes we want to add a page under different subsites (or main site) in a subsite's nav. While linking with ../ may work, but mkdocs can't properly process as it can't find the page.

It shows error like
`WARNING  -  A relative path to 'test/../cross.md' is included in the 'nav' configuration, which is not found in the documentation files`

And the navigation title will be None.

This PR fixes it by having normpath for nav link.

2023-02-22 08:38 UTC, agentbellnorm approved these changes
Looks good to me, thanks!

2023-02-23 08:22 UTC, agentbellnorm requested changes
Hi again, I was a bit quick - can you update the changelog and the version in `setup.py`?

Not sure why the checks are not running. Let's see what happens when you push new changes.

2023-02-24 22:13 UTC, haneul commented
okay updated

2023-02-27 15:12 UTC, agentbellnorm approved these changes

2023-02-27 16:29 UTC, agentbellnorm commented
Seems like a test needs updated.

2024-01-04 14:34 UTC, bih commented
@haneul Can you go ahead and update the test? I can go ahead and merge this once that's resolved :)

2025-03-17 11:57 UTC, MABERG13-github commented
Hi @bih any update on this one

2025-06-05 18:31 UTC, bih commented
Closing this as not mentioned in a while and considering stale.

2025-06-05 18:31 UTC, closed without merging